User story 5
PhilipDeFraties/monster_shop_2005 pull request #63
Opened 2020-09-10 03:21 UTC by dhalverson

**Adds**

- User model tests
- Updates nav bar to include admin view logic
- Adds admin routes
- Creates admin dashboard and user HTML placeholders
- Adds enum roles to user
- Creates admin controller

2020-09-10 03:36 UTC, dhalverson commented on spec/features/navigation_spec.rb
> +  describe 'As an Admin' do
Need to add other types of users to this test for edge cases

2020-09-10 03:36 UTC, dhalverson commented on spec/models/user_spec.rb
> +  describe "roles" do
Need to test methods here as well

2020-09-10 03:39 UTC, dhalverson reviewed
Need to update feature and model tests for this PR

2020-09-10 03:39 UTC, dhalverson commented on spec/models/user_spec.rb
> +  describe "roles" do
Need to test the methods here

2020-09-10 03:39 UTC, dhalverson commented on spec/features/navigation_spec.rb
> +  describe 'As an Admin' do
Need to test edge case here, to test other types of users

2020-09-10 14:51 UTC, PhilipDeFraties commented on app/controllers/admins_controller.rb
> +class AdminsController < ApplicationController
Admin::DashboardController < Admin::BaseController I think will be the first line

2020-09-10 14:58 UTC, PhilipDeFraties requested changes
Looks good, I think you did the migration correctly. Just gotta look at the admin controllers and figure out the base/dashboard stuff.

2020-09-10 15:22 UTC, PhilipDeFraties commented on config/routes.rb
> +  get '/admin', to: 'admins#dashboard'
I think the routes here are a bit off, I dont think dashboard is supposed to be an action, I believe the route would look like this: 
`get '/merchant/dashboard', to: "dashboard#index"`

2020-09-11 00:13 UTC, closed without merging

2020-09-11 00:14 UTC, dhalverson commented
Awaiting US 8 PR to add this content